name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Adding Checkout Actions
              uses: actions/checkout@v4
            - name: Welcome to step1
              run: echo "My Fisrt Github Actions Job"
            - name: List files
              run: ls
            - name: Reading readme file
              run: cat README.md
            - name: Show Ansible version
              run: ansible --version   #it ran because ansible was pre-installed in this runner image

            - name: CHeck Terraform version
              run: terraform --version

            - name: CHeck Jenkins status 
              run: sudo service jenkins status
            

